
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global

namespace FSInteractiveAndroid
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnExceptione603ea75cb2849e99462ac8a967ced89 of obj
    exception ReturnNoneExceptione603ea75cb2849e99462ac8a967ced89
    [<AutoOpen>]
    module FuncConvertFinalOverloade603ea75cb2849e99462ac8a967ced89 =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>]
        
        (* partial *)Resource = class
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            static member UpdateIdValues  () =
                ()
        end
    
    and
        
        (* partial *)Resource_Attribute = class
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            new() as this =
                {
                }
        end
    
    and
        
        (* partial *)Resource_Drawable = class
            // aapt resource value: 0x7f020000
            static member Icon = 2130837504
            
            // aapt resource value: 0x7f020001
            static member monoandroidsplash = 2130837505
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            new() as this =
                {
                }
        end
    
    and
        
        (* partial *)Resource_Id = class
            // aapt resource value: 0x7f060000
            static member myButton = 2131099648
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            new() as this =
                {
                }
        end
    
    and
        
        (* partial *)Resource_Layout = class
            // aapt resource value: 0x7f030000
            static member Main = 2130903040
            
            // aapt resource value: 0x7f030001
            static member monoandroidsplash = 2130903041
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            new() as this =
                {
                }
        end
    
    and
        
        (* partial *)Resource_String = class
            // aapt resource value: 0x7f040001
            static member app_name = 2130968577
            
            // aapt resource value: 0x7f040000
            static member hello = 2130968576
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            new() as this =
                {
                }
        end
    
    and
        
        (* partial *)Resource_Style = class
            // aapt resource value: 0x7f050000
            static member Mono_Android_Theme_Splash = 2131034112
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            new() as this =
                {
                }
        end